<?php

/**
 * UzenetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UzenetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UzenetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Uzenet');
    }
}