<?php

/**
 * KategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Kategoria');
    }
}